// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: types/order.proto

// имя proto-пакета и версия
// версию указывать необязательно, это общепринятый подход
// для версионирования спецификации

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// описание типа Order
type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orderid                    int64                  `protobuf:"varint,1,opt,name=orderid,proto3" json:"orderid,omitempty"` // Go: []byte
	Userid                     int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`   // Go: bool
	Status                     string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Goods                      []*Goods               `protobuf:"bytes,4,rep,name=goods,proto3" json:"goods,omitempty"`                                                               // Go: []Goods
	Ordersum                   float64                `protobuf:"fixed64,5,opt,name=ordersum,proto3" json:"ordersum,omitempty"`                                                       //Go: double
	Accrualsum                 float64                `protobuf:"fixed64,6,opt,name=accrualsum,proto3" json:"accrualsum,omitempty"`                                                   //Go: double
	Withdrawalsum              float64                `protobuf:"fixed64,7,opt,name=withdrawalsum,proto3" json:"withdrawalsum,omitempty"`                                             //Go: double
	UploadedAt                 *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`                                   //Go: time.Time
	ProcessedByAccrualAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=processed_by_accrual_at,json=processedByAccrualAt,proto3" json:"processed_by_accrual_at,omitempty"` //Go: time.Time
	UploadedAtString           string                 `protobuf:"bytes,10,opt,name=uploaded_at_string,json=uploadedAtString,proto3" json:"uploaded_at_string,omitempty"`
	ProcessedByAccrualAtString string                 `protobuf:"bytes,11,opt,name=processed_by_accrual_at_string,json=processedByAccrualAtString,proto3" json:"processed_by_accrual_at_string,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_types_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_types_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderid() int64 {
	if x != nil {
		return x.Orderid
	}
	return 0
}

func (x *Order) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *Order) GetOrdersum() float64 {
	if x != nil {
		return x.Ordersum
	}
	return 0
}

func (x *Order) GetAccrualsum() float64 {
	if x != nil {
		return x.Accrualsum
	}
	return 0
}

func (x *Order) GetWithdrawalsum() float64 {
	if x != nil {
		return x.Withdrawalsum
	}
	return 0
}

func (x *Order) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Order) GetProcessedByAccrualAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedByAccrualAt
	}
	return nil
}

func (x *Order) GetUploadedAtString() string {
	if x != nil {
		return x.UploadedAtString
	}
	return ""
}

func (x *Order) GetProcessedByAccrualAtString() string {
	if x != nil {
		return x.ProcessedByAccrualAtString
	}
	return ""
}

// описание типа Goods
type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string  `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"` // Go: string
	Accrualsum  int64   `protobuf:"varint,2,opt,name=accrualsum,proto3" json:"accrualsum,omitempty"`  // Go: int64
	Price       float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`           // Go: double
}

func (x *Goods) Reset() {
	*x = Goods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_types_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_types_order_proto_rawDescGZIP(), []int{1}
}

func (x *Goods) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Goods) GetAccrualsum() int64 {
	if x != nil {
		return x.Accrualsum
	}
	return 0
}

func (x *Goods) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AccrualReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order   string  `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Status  string  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Accrual float64 `protobuf:"fixed64,3,opt,name=accrual,proto3" json:"accrual,omitempty"`
}

func (x *AccrualReply) Reset() {
	*x = AccrualReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccrualReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccrualReply) ProtoMessage() {}

func (x *AccrualReply) ProtoReflect() protoreflect.Message {
	mi := &file_types_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccrualReply.ProtoReflect.Descriptor instead.
func (*AccrualReply) Descriptor() ([]byte, []int) {
	return file_types_order_proto_rawDescGZIP(), []int{2}
}

func (x *AccrualReply) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *AccrualReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccrualReply) GetAccrual() float64 {
	if x != nil {
		return x.Accrual
	}
	return 0
}

type GetOrdersItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number     string  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Status     string  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Accrual    float64 `protobuf:"fixed64,3,opt,name=accrual,proto3" json:"accrual,omitempty"`
	UploadedAt string  `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
}

func (x *GetOrdersItem) Reset() {
	*x = GetOrdersItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersItem) ProtoMessage() {}

func (x *GetOrdersItem) ProtoReflect() protoreflect.Message {
	mi := &file_types_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersItem.ProtoReflect.Descriptor instead.
func (*GetOrdersItem) Descriptor() ([]byte, []int) {
	return file_types_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersItem) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetOrdersItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrdersItem) GetAccrual() float64 {
	if x != nil {
		return x.Accrual
	}
	return 0
}

func (x *GetOrdersItem) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

var File_types_order_proto protoreflect.FileDescriptor

var file_types_order_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x03, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x75, 0x6d, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x75, 0x6d, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x75, 0x6d, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x75, 0x6d, 0x12,
	0x24, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x73, 0x75, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x61, 0x6c, 0x73, 0x75, 0x6d, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x51, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x14, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x42, 0x79, 0x41, 0x63, 0x63, 0x72,
	0x75, 0x61, 0x6c, 0x41, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x42, 0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x5f, 0x62, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x5f, 0x61, 0x74, 0x5f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x42, 0x79, 0x41, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x41,
	0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x5f, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73,
	0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x72,
	0x75, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c,
	0x22, 0x7a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41, 0x74, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_order_proto_rawDescOnce sync.Once
	file_types_order_proto_rawDescData = file_types_order_proto_rawDesc
)

func file_types_order_proto_rawDescGZIP() []byte {
	file_types_order_proto_rawDescOnce.Do(func() {
		file_types_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_order_proto_rawDescData)
	})
	return file_types_order_proto_rawDescData
}

var file_types_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_order_proto_goTypes = []interface{}{
	(*Order)(nil),                 // 0: types.v1beta1.Order
	(*Goods)(nil),                 // 1: types.v1beta1.Goods
	(*AccrualReply)(nil),          // 2: types.v1beta1.AccrualReply
	(*GetOrdersItem)(nil),         // 3: types.v1beta1.GetOrdersItem
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_types_order_proto_depIdxs = []int32{
	1, // 0: types.v1beta1.Order.goods:type_name -> types.v1beta1.Goods
	4, // 1: types.v1beta1.Order.uploaded_at:type_name -> google.protobuf.Timestamp
	4, // 2: types.v1beta1.Order.processed_by_accrual_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_order_proto_init() }
func file_types_order_proto_init() {
	if File_types_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Goods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccrualReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_order_proto_goTypes,
		DependencyIndexes: file_types_order_proto_depIdxs,
		MessageInfos:      file_types_order_proto_msgTypes,
	}.Build()
	File_types_order_proto = out.File
	file_types_order_proto_rawDesc = nil
	file_types_order_proto_goTypes = nil
	file_types_order_proto_depIdxs = nil
}
